#### Equality

```{r}
"Rchitect" != "rchitect"
TRUE == FALSE
-6 * 14 != 17 - 101
TRUE == 1

-6 * 5 + 2 >= -10 + 1
"raining" <= "raining dogs" # Compare the length of strings
TRUE < FALSE
```

#### Compare Vectors

```{r}
linkedin = c(16, 9, 13, 5, 2, 17, 14)
facebook = c(17, 9, 16, 5, 3, 13, 14)

linkedin > 15 # Compare each element and return a Boolean
facebook <= 5

linkedin > facebook # Compare between elements, it is necessary that each structure have the same numbers of elements.
```

#### Compare matrices

```{r}
views <- matrix(c(linkedin, facebook), nrow=2, byrow=TRUE)
views

views == 13
```

#### & and \|

```{r}
linkedin
last <- tail(linkedin, 1) # Last n elements

last > 5 | last > 10
last > 15 & last <= 20

linkedin > 10

linkedin > 10 & facebook < 10
linkedin >= 12 | facebook >= 12
```

#### The if statement

```{r}
medium = "Facebook"
num_views = 14

if(medium == "Linked"){
  print("Showing Linkedin information")
} else if (medium == "Facebook") {
  print("Showing FAcebook information")
} else {
  print("unkown medium")
}

if (num_views > 15){
  print("You are popular")
} else if(num_views <= 15 & num_views > 10){
  print("Your number of views is average")
} else {
  print("Try to be more visible")
}
```

```{r}
result <- ""
number <- 101

if (number < 10) {
  if (number < 5) {
    result <- "extra small"
  } else {
    result <- "small"
  }
} else if (number < 100) {
  result <- "medium"
} else {
  result <- "large"
}

print(result)
```

#### Write a while loop

```{r}
speed = 64

while (speed > 30) {
  print("Slow down!")
  speed <- speed - 7
}
speed
```

```{r}
speed = 64

while (speed > 30) {
  print(paste("Your speed is", speed))
  if (speed >= 48) {
    print("Slow down big time!")
    speed <- speed - 11
  } else {
    print("Slow down!")
    speed <- speed - 6
  }
}

speed
```

#### Stop the while loop: break

```{r}
speed = 75

while (speed > 30) {
  print(paste("YOur speed is", speed))
  
  if (speed > 80) {
    break
  }
  
  if (speed > 48) {
    print("Slow down bi time!")
    speed <- speed - 11
  } else {
    print("slow down!")
    speed <- speed - 6
  }
}
```

#### Build a while loop from scratch

```{r}
i <- 1

while (i <= 10) {
  print(3*i)
  if ((i*3) %% 8 == 0) {
    break
  }
  i <- i + 1
}
```

# For loop

## Loop over a vector

```{r}
linkedin <- c(16,9,13,5,2,17,14)

for (l in linkedin) {
  print(l)
}

for (i in 1:length(linkedin)) {
  print(linkedin[i])
}
```

## Loop over a list

```{r}
nyc = list(pop = 8405837, boroughs = c("Manhathan", "Bronx", "Brooklyn", "Queens", "Staten Island"), capital=FALSE)

for (l in nyc) {
  print(l)
}

for (i in 1:length(nyc)) {
  print(nyc[[i]])
}
```

## Loop over a matrix

```{r}
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

box_office <- c(new_hope, empire_strikes, return_jedi)
box_office

stars_wars_matrix <- matrix(box_office, byrow = TRUE, nrow = 3)
stars_wars_matrix
```

```{r}
for (i in 1:nrow(stars_wars_matrix)){
  for (j in 1:ncol(stars_wars_matrix)){
    print(paste("on row", i, "and column", j, "the board contains", stars_wars_matrix[i,j]))
  }
}
```

## Loop & conditional

```{r}
linkedin <- c(16,9,13,5,2,17,14)

for (li in linkedin){
  if (li > 10) {
    print("You're popular!")
  } else {
    print("Be more visible!")
  }
  if (li > 16) {
    print("This is ridiculous, I'm outta here!")
    break
  }
  if (li > 5){
    print("This is too embarrasing!")
  }
  print(li)
}
```
